### ISSUE TITLE
Should we use an organization instead of normal user account?

### ISSUE THREAD

**Issue by hackerncoder** [TheWallStreetAnalytics/wallstreetanalytics#15]
Having an organization instead of user account may be beneficial, especially if we are going to have more than one repository. There have been talks of that a few places: https://github.com/WallStreetBetsAnalytics/wallstreetbets/pull/12 https://github.com/WallStreetBetsAnalytics/wallstreetbets/pull/5#issuecomment-781791767 https://github.com/WallStreetBetsAnalytics/wallstreetbets/issues/14.

An unknown person has registered an organization with the name WallStreetBetsAnalytics (please identify yourself). To ensure there was at least one I have registered WSBAnalytics.

**Comment by athielen** [comment]
@hackerncoder User and Organizations are in the same pool. So @itsclaireh would have to change the name of this account (at a low traffic time when everyone is asleep ;) ) and create an organization after wards to get 'WallStreetBetsAnalytics'  name.

**Comment by hackerncoder** [comment]
Could you write that in more plain-english?

**Comment by hackerncoder** [comment]
What do you mean "in the same pool"? Why would [pers](https://stallman.org/articles/genderless-pronouns.html) have to do that? The name seems to have been taken so I don't get how that would work.

**Comment by ImmaZoni** [comment]
This worries me as it's not very decentralized

**Comment by athielen** [comment]
@hackerncoder There can't be a user with the same name as an organization. The person who took the name is this user.

**Comment by TheWallStreetAnalytics** [comment]
@hackerncoder It's the admins with these accounts.

**Comment by hackerncoder** [comment]
@athielen I understood that this morning. 5 AM is not a good time to be doing stuff.

Also, you talk of a discord. So here is my name: Firststrike#1462

**Comment by Mantosh** [comment]
+1 from me.

I've seen this being discussed on discord too.

**Comment by hackerncoder** [comment]
I really gotta get on the Discord, how do I?

**Comment by dylanhitt** [comment]
Way to early lurker here.

I would also like to get involved in this discord. I would like to work on infrastructure side of things, whether it be for home labs or if anything publicly hosted manifests out of this. Also +1 to move to an Org.

**Comment by TheWallStreetAnalytics** [comment]
@hackerncoder sent you a friend request on discord so I can invite you.
@dylanhitt can you post your discord name?

**Comment by dylanhitt** [comment]
I'll have to delete this after the invite. I hope you enjoy my degen name. `zeDonald#6759`.
