### ISSUE TITLE
I picked up the domain wallstreetanalytics.org

### ISSUE THREAD

**Issue by qcasey** [TheWallStreetAnalytics/wallstreetanalytics#32]
I'll point DNS to wherever. Or transfer if there's actually an organization here

**Comment by JackDawsen** [comment]
Hey there - thank you for doing this! We're still formulating a name and hopefully that happens soon. We'll update you here when that happens!

**Comment by kentimusrex** [comment]
if you want to setup a forwarding domain (if you are using google) to this github organization that would be good. Looks like https;//wallstreetanalytics.io is already pointed this org already
