### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by Carter-Nichols** [TheWallStreetAnalytics/wallstreetanalytics#42]
Github has gone quiet these past few days. Is all discussion taking place on discord? The link I recieved was invalid and I'm not receiving any replies to my email asking for a fresh one.

**Comment by itsclaireh** [comment]
Hey! I am so sorry I didn't get back to you--I've been trying to get to everyone but didn't want to send out a general link yet until we had a bot in place to prevent spam. We have that now, so this link should continue to work: [https://discord.gg/sDWtN6Bs56](https://discord.gg/sDWtN6Bs56)

All discussion is taking place on discord for the time being. We are at a point where we are selecting our technical leaders/SMEs/git admins, and they will be setting project requirements.

**Comment by Carter-Nichols** [comment]
Oh no it's okay, I understand. Thanks a lot for the quick response and discord link! See you in discord.
