### ISSUE TITLE
data science / machine learning / NLP as separate subject areas ??

### ISSUE THREAD

**Issue by bici-sancta** [TheWallStreetAnalytics/wallstreetanalytics#43]
Thanks for publishing the updates on this project.

I have a question about the distinct categorization of data science, machine learning, and NLP within this project.

- Is there a need to have these as 3 separate teams ?
- Is there sufficient clarity expressed somewhere about the distinct role of these separate teams ?
- NLP is typically considered a method within the construct of machine learning ... does the current proposed team structure imply that machine learning includes all machine learning methods except NLP ?
- if there are to be 3 (or 2) distinct teams here, what is thought on managing overlap/boundaries among these teams ?
- are the SMEs for NLP, machine learning, and data science in agreement with this structure ?

Just trying to be helpful here .... I propose some consideration be given to clarity around the current proposed team structure, or collapsing to fewer subject areas, with some hierarchical structure indicated, e.g., identify NLP as a specific team within the umbrella of the machine learning team.

**Comment by kentimusrex** [comment]
1. Yes, it was decided that these are separate areas that have overlap however the SME are considered experts in their respective areas.

2. I am not sure, I would ping Claire

3. NLP is not a construct within machine learning, it leverages machine learning in some of its applications. ML and NLP both fall under AI and have been fairly distinct fields for quite a long time. It would depend on the ML techniques being used, but if there were ML techniques that would be looking at NLP topics you would probably look at the NLP group for discussion/assistance/etc.

4. The SMEs talk with one another and if there are questions, please engage any of them.

5. Yes
